enabled: true
top_level_version: false
google_analytics_code: UA-57261294-2
home_url: www.daocloud.io
github:
  position: top
  tree: 'https://github.com/DaoCloud/daocloud-docs/blob/master/'
  commits: 'https://github.com/DaoCloud/daocloud-docs/commits/develop/'
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/learn4
